config/routes.rb
Rails.application.routes.draw do
  root to: 'home#index'

  devise_for :users

  get :driverapp, to: "drivers#index" do

  end
  
  get :customerapp, to: "customers#index" do
 
  end

  get :dashboard, to: "dashboard#index"

  namespace :api do
  	namespace :one do
  		resources :cab_requests	do
  			member do 
  				post "process_request"
  			end
  		end
  	end
  end
end

app/controllers/customers_controller.rb
class CustomersController < ApplicationController

	def index
		
	end
end

app/helpers/customers_helper.rb
module CustomersHelper
end

app/views/customers/index.html.erb
<%= form_tag("#", method: "post", id: "cab-request-form") do %>
  <%= label_tag(:customer_id, "Enter Customer Id") %>
  <%= text_field_tag(:customer_id, "", placeholder: "Customer Id", required: true) %>
  
  <br>
  <%= label_tag(:latitude, "Enter X location") %>
  <%= number_field_tag(:latitude, "", placeholder: "X", required: true) %>

  <br>
  <%= label_tag(:longitude, "Enter Y location") %>
  <%= number_field_tag(:longitude, "", placeholder: "Y", required: true) %>
  <br>
  <br>
  <%= submit_tag("Submit") %>
<% end %>

<script>
	$("#cab-request-form").on("submit", function(){
		var formData = {customer_id: $("#customer_id").val(), latitude: $("#latitude").val(), longitude: $("#longitude").val()}
		
		$.ajax({
			method: "POST",
			url: "<%= api_one_cab_requests_path %>",
		  	data: formData
		})
		.done(function( response ) {
		   alert("cab request " + response.message + ". Cab Request Id is: " + response.cab_request_id) 
		})
		.fail(function( response ){
			alert("failed because: " + response.responseJSON.reason)
		});
		return false
	})

	var appendrequest = function(request){

	}

</script>